version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  users-service:
    build:
      context: ./usersServices
      dockerfile: Dockerfile
    container_name: users-service
    restart: always
    ports:
      - "5010:5010"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/usersdb
    env_file:
      - ./usersServices/.env
    depends_on:
      - mongo

  task-service:
    build:
      context: ./taskServices
      dockerfile: Dockerfile
    container_name: task-service
    restart: always
    ports:
      - "5011:5011"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/tasksdb
    env_file:
      - ./taskServices/.env
    depends_on:
      - mongo

volumes:
  mongo_data:
